### ISSUE TITLE
BUG: HandleJoin crashes when a user comes back

### ISSUE THREAD

**Issue by fahadash** [SirCmpwn/ChatSharp#54]
When a user QUITs and joins back, the following line crashes
https://github.com/SirCmpwn/ChatSharp/blob/master/ChatSharp/Handlers/ChannelHandlers.cs#L15

Attached is the log of the bot. A good solution would be to remove the user entirely from the user collection once he/she quits.
[chatsharp_bot_log.txt](https://github.com/SirCmpwn/ChatSharp/files/131337/chatsharp_bot_log.txt)

**Comment by DaZombieKiller** [comment]
I mentioned the fix for this bug here: https://github.com/SirCmpwn/ChatSharp/pull/57#issuecomment-202685890

**Comment by Jan1902** [comment]
Has someone found a fix for that yet, or will there be an official one ?

**Comment by RockyTV** [comment]
This is a hard one to tackle. There are at least three different ways for storing the client's channel list: `IrcClient.Channels`, `IrcClient.User.Channels` and `IrcClient.Users[User.Nick].Channels`. I can think of two solutions: either all of these should be merged into a single one, or only one of them must exist while the other two have references to the channel list, instead of handling the channel list separately.

**Comment by SirCmpwn** [comment]
Let's not make breaking changes, but I'm all for unifying the stores.

**Comment by fahadash** [comment]
OR, let's write unit tests.

**Comment by RockyTV** [comment]
@fahadash I spent a day and a half trying to fix this issue, with some results. I managed to fix the `PART` bug, but now there's another bug: when the client joins a channel with at least one user in it, it will throw trying to parse the other user's modes.

The reason for the `PART` bug was simple: the parted channel would be removed from the channel list before the `PART` message could be parsed.
